### ISSUE TITLE
Next Button

### ISSUE THREAD

**Issue by contraptsean** [jrmeyerhofer/LITA2017#1]
I found myself wanting a next button at the bottom of the tutorial page during the presentation to avoid scrolling to the top and using the breadcrumbs (I'm v lazy).

**Comment by jrmeyerhofer** [comment]
Thanks for the comment. And it makes total sense. I'll add them!

**Comment by contraptsean** [comment]
Hey John, no problem. I really enjoyed your presentation! I feel like I
probably talked too much in it. I'll be in touch about the script vs
function calls.
-Sean

On Nov 11, 2017 11:07 AM, "jrmeyerhofer" <notifications@github.com> wrote:

Thanks for the comment. And it makes total sense. I'll add them!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jrmeyerhofer/LITA2017/issues/1#issuecomment-343683199>,
or mute the thread

**Comment by jrmeyerhofer** [comment]
Added the "next" button at the bottom using lesson links.
